dhis2/event-reports-app

package.json
src/css/style.css
webpack-base-config.js
yarn.lock

* **Issue:** Closes [DHIS2-5492](https://jira.dhis2.org/browse/DHIS2-5492) and [DHIS2-5494](https://jira.dhis2.org/browse/DHIS2-5494)
* **Requires:** https://github.com/dhis2/d2-analysis/pull/90

Add webpack infrastructure and styles for d2-ui-rich-text

---

package.json
yarn.lock

chore: Upgrade d2-analysis dependency [v32]

---

package.json
yarn.lock

chore: Upgrade d2-analysis dependency [v31]

---

package.json
src/api/Layout.js
src/ui/AggregateLayoutWindow.js
yarn.lock

Relates to [DHIS2-5258](https://jira.dhis2.org/browse/DHIS2-5258).
- Adding support for org unit field.
- Updating `d2-analysis` version to include org unit field code.

feat: Add support for org unit field

---

package.json
src/manager/AppManager.js
yarn.lock

Fixes [DHIS2-6868](https://jira.dhis2.org/browse/DHIS2-6868).
- Requesting `legendSet` for dataElementDimensions layout property
- Including latest d2-analysis version

fix: saving multiple data element filters

---

package.json
yarn.lock

fix: Saving multiple data element filters [v31]

---

package.json
yarn.lock

fix: Saving multiple data element filters [v32]

---

package.json
yarn.lock

fix: Saving multiple data element filters [v30]

---

index.html
src/css/style.css

fix: Make styles more specific to app/plugin [v33]

---

src/api/Layout.js

Correctly set start/end dates and paging for line list downloads.

fix: dates and paging for line lists

---

src/api/Layout.js

Set dataIdScheme=NAME for table layout.

fix: set data id scheme

---

package.json
yarn.lock

Fixes https://github.com/dhis2/d2-analysis/commit/12e1e0ec2c6fb9759a384984bc1b57969b319a69

fix: d2-analysis@33.2.18 [v34] (DHIS2-9839)

---

package.json
yarn.lock

Fixes https://github.com/dhis2/d2-analysis/commit/12e1e0ec2c6fb9759a384984bc1b57969b319a69

fix: d2-analysis@33.2.18 [v35] (DHIS2-9839)

---

package.json
yarn.lock

Fixes https://github.com/dhis2/d2-analysis/commit/12e1e0ec2c6fb9759a384984bc1b57969b319a69

fix: d2-analysis@33.2.18 [v33] (DHIS2-9839)

---

i18n/en.pot
src/components/Dialogs/Conditions/BooleanCondition.js
src/components/Dialogs/Conditions/ConditionsManager.js
src/components/Dialogs/Conditions/NumericCondition.js
src/components/Dialogs/Conditions/styles/Condition.module.css

Implements [TECH-815](https://jira.dhis2.org/browse/TECH-815)
Spec: [ER:C6: Condition selector](https://docs.google.com/document/d/1qrcLpVymdBpgzJyJ3IPULtotCQdg2PWnQL-AlgntMz4/edit#)
---
1. Implement boolean conditions
---
Follows the pattern used for the numeric and alphanumeric conditions. However a new concept, `SINGLETON_TYPES` was introduced, as booleans + others (e.g. option sets) will only have a single fixed condition (e.g. "Add another condition" doesn't apply), which shows/hides the affected ui elements accordingly.
---

feat: boolean conditions (TECH-815)

---

i18n/en.pot
src/components/Dialogs/Conditions/AlphanumericCondition.js
src/components/Dialogs/Conditions/ConditionsManager.js
src/components/Dialogs/Conditions/styles/Condition.module.css

Implements [TECH-812](https://jira.dhis2.org/browse/TECH-812)
Spec: [ER:C6: Condition selector](https://docs.google.com/document/d/1qrcLpVymdBpgzJyJ3IPULtotCQdg2PWnQL-AlgntMz4/edit#)
---
1. Implement alphanumeric conditions
---
Based on the recent implementation of numeric conditions. Plus some added logic for the case sensitive (CS), as CS operators are regular operators but needs to be joined with the non-CS counterparts (`SingleSelect` only allows passing in a `selected` that's actually in the list of children, so had to map the CS and non-CS together).
---
-   [ ] Analytics requests using most operators (e.g. `ILIKE`) doesn't work (lack of backend support?)
---

feat: alphanumeric conditions (TECH-812)

---

package.json
src/components/Visualization/Visualization.js
yarn.lock

Requires: https://github.com/dhis2/analytics/pull/1080.

feat: format numeric values with digit group separator

---

src/actions/ui.js
src/reducers/__tests__/ui.spec.js
src/reducers/ui.js

Reducer, action, selectors and tests for `repetition`.

fix: repetition infrastructure

---

src/components/Visualization/useAnalyticsData.js

Fixes [TECH-892](https://jira.dhis2.org/browse/TECH-892).
1. Implement a simplified processing of the analytics response for LL
---
The AnalyticsResponse object does a lot of processing of the analytics
response which is not needed for ER Line List.
Instead, only convert booleans values to Yes/No and use ouname column
values for the ou column.
---
Before:
After:

refactor: replace AnalyticsResponse with a simplified version

---

package.json
src/components/App.js
src/components/DetailsPanel/DetailsPanel.js
src/components/Toolbar/MenuBar/MenuBar.js
src/components/Toolbar/Toolbar.js
yarn.lock

Implements [TECH-949](https://jira.dhis2.org/browse/TECH-949)
Update the app according to backend migration: https://jira.dhis2.org/browse/DHIS2-12393

feat: switch from eventReport to eventVisualization

---

src/actions/ui.js
src/components/App.js
src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
src/components/MainSidebar/ProgramDimensionsPanel/StageSelect.js

Partially implements [TECH-874](https://jira.dhis2.org/browse/TECH-874)
---
1. Stores program in metadata store
2. Stores program stage in metadata store
3. The fields filter for two queries has been updated so that the required fields are present
---
Selected program and program stage are stored either when they are selected, or when a saved visualization is loaded. More work needs to be done in the main sidebar but this work is presented as a separate PR as it is needed by other team members.
---

feat: store program and program stage in metadata store

---

i18n/en.pot
src/api/legendSets.js
src/components/Dialogs/Conditions/ConditionsManager.js
src/components/Dialogs/Conditions/OptionSetCondition.js

Implements [TECH-787](https://jira.dhis2.org/browse/TECH-787)
---
1. Adds metadata to prevent optionSets from crashing when creating a new AO + prevent `addMetadata` to be fired for already added options
2. Throws a proper error for unsupported dimension types (fix to prevent this from actually happening TBD)
3. Filters out unsupported valueTypes
4. Adds the valueType and dimensionType to the modal title for test purposes

fix: various bugs with conditions (TECH-787)

---

src/actions/ui.js
src/components/App.js
src/components/MainSidebar/TimeDimensions.js
src/components/MainSidebar/__tests__/TimeDimensions.spec.js
src/components/MainSidebar/__tests__/__snapshots__/TimeDimensions.spec.js.snap

Implements [TECH-804](https://jira.dhis2.org/browse/TECH-804)
---
1. fix crash due to missing object. If metadata is missing then `stage` should be set to a default object

fix: set stage to default object in case metadata is not present

---

src/actions/loader.js
src/components/App.js
src/components/Visualization/StartScreen.js

Implements [TECH-706](https://jira.dhis2.org/browse/TECH-706)
---
1. Shows an error message when trying to load an AO that isn't found
---

feat: error message for AO not found (TECH-706)

---

src/components/Visualization/StartScreen.js

Implements [TECH-970](https://jira.dhis2.org/browse/TECH-970)
Adds instructions.
After:

fix: add start screen instructions (TECH-970)

---

src/components/App.js

programType is needed to determine which Time dimensions should be enabled

fix: include programType in eventVisualizations request

---

i18n/en.pot
src/components/MainSidebar/DimensionItem/DimensionItem.js
src/components/MainSidebar/DimensionItem/DimensionItem.module.css
src/components/MainSidebar/MainDimensions.js
src/components/MainSidebar/MainSidebar.js
src/components/MainSidebar/MainSidebar.module.css
src/components/MainSidebar/MainSidebarSection.js
src/components/MainSidebar/MainSidebarSection.module.css
src/components/MainSidebar/TimeDimensions.js
src/components/MainSidebar/__tests__/TimeDimensions.spec.js
src/components/MainSidebar/__tests__/__snapshots__/TimeDimensions.spec.js.snap
src/components/Visualization/StartScreen.js
src/modules/dimensionTypes.js

Implements [DHIS2-TECH-962](https://jira.dhis2.org/browse/DHIS2-TECH-962)
---
1. Add main dimensions section to main sidebar
2. Extract `MainSidebarSection` to allow style sharing between the time and main dimsnions section
---
_supporting text_

feat: add main dimensions section to main sidebar

---

src/components/MainSidebar/DimensionItem/DimensionItem.js
src/modules/dimensionTypes.js
src/modules/metadata.js
src/modules/timeDimensions.js
src/modules/visualization.js

Quick fix so all period dimensions have period type `PERIOD`

fix: set periodType field on period dimensions to `PERIOD`

---

src/components/Layout/LineListLayout/styles/LineListLayout.module.css

Changes the column-filter width to 65-35 for line lists.

fix: layout axis width

---

src/components/Visualization/Visualization.js

1. lookup value in metadata for `programStatus`
2. lookup value in metadata for `eventStatus`
---
This is to avoid the ids to be displayed in the data table instead of the corresponding names.
Before:
After:

fix: lookup row value in metadata for program and event status

---

src/components/Dialogs/FixedDimension.js
src/modules/visualization.js

fix: event status

---

src/components/App.module.css

fix: scrollbar css

---

src/components/Visualization/Visualization.js

Implements [TECH-984](https://jira.dhis2.org/browse/TECH-984)
---
1. show repetition in headers' labels
---
See screenshots.
---

feat: show repetition in headers (TECH-984)

---

src/components/MainSidebar/ProgramDimensionsPanel/useProgramDimensions.js
src/components/MainSidebar/YourDimensionsPanel/useYourDimensions.js

Implements [TECH-1004](https://jira.dhis2.org/browse/TECH-1004)
---
1. sort program dimension listst alphabetically
2. sort your dimension listst alphabetically
---
_Program dimensions_
_Your dimensions_

fix: sort dimension listst alphabetically

---

package.json
src/api/Dimension.js
src/api/Layout.js
src/index.js
src/manager/InstanceManager.js
src/plugin.js
src/ui/DataTypeToolbar.js
src/ui/QueryLayoutWindow.js
yarn.lock

Backport of 26c46b7e16c3eaf858eaf2b97a3e2e41e66dd945

fix: backport of (#1019)

---

package.json
src/api/Dimension.js
src/api/Layout.js
src/index.js
src/manager/InstanceManager.js
src/plugin.js
src/ui/DataTypeToolbar.js
src/ui/QueryLayoutWindow.js
yarn.lock

Backport of 26c46b7e16c3eaf858eaf2b97a3e2e41e66dd945

fix: backport of #1019

---

.github/workflows/dhis2-verify-app.yml

Installs libpng-dev which is needed by pngquant.

chore: install prerequisites

---

package.json
yarn.lock

Implements [DHIS2-11233](https://jira.dhis2.org/browse/DHIS2-11233)
See description in the Jira ticket.
[DHIS2-11233]: https://dhis2.atlassian.net/browse/DHIS2-11233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: analytics@33.2.28 due/scheduled date

---

package.json
yarn.lock

Implements [DHIS2-11233](https://jira.dhis2.org/browse/DHIS2-11233)
See description in the Jira ticket.
[DHIS2-11233]: https://dhis2.atlassian.net/browse/DHIS2-11233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: analytics@33.2.28 v38

---

package.json
yarn.lock

Implements [DHIS2-11233](https://jira.dhis2.org/browse/DHIS2-11233)
See description in the Jira ticket.
[DHIS2-11233]: https://dhis2.atlassian.net/browse/DHIS2-11233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: analytics@33.2.28 v39

---

package.json
yarn.lock

Implements [DHIS2-11233](https://jira.dhis2.org/browse/DHIS2-11233)
See description in the Jira ticket.
[DHIS2-11233]: https://dhis2.atlassian.net/browse/DHIS2-11233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: analytics@33.2.28 v40

---

package.json
src/ui/DownloadButtonItems.js
yarn.lock

This reverts commit 7765296b168d882029f9f25e444471c45975741d.

Revert "feat: add class-name for push-analytics (#1241)"

---

package.json
yarn.lock

Implements [DHIS2-15816](https://jira.dhis2.org/browse/DHIS2-15816)
[DHIS2-15816]: https://dhis2.atlassian.net/browse/DHIS2-15816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: d2-analysis@33.3.1 apply filter when restoring data items (DHIS2-15816)

---

package.json
yarn.lock

Backports https://github.com/dhis2/event-reports-app/pull/1283

fix: d2-analysis@33.3.1 apply filter when restoring data items (DHIS2-15816) [v41]

---

package.json
yarn.lock

Backports https://github.com/dhis2/event-reports-app/pull/1283

fix: d2-analysis@33.3.1 apply filter when restoring data items (DHIS2-15816) [v40]

---

package.json
yarn.lock

Backports https://github.com/dhis2/event-reports-app/pull/1283

fix: d2-analysis@33.3.1 apply filter when restoring data items (DHIS2-15816) [v39]

---

package.json
yarn.lock

Backports https://github.com/dhis2/event-reports-app/pull/1283

fix: d2-analysis@33.3.1 apply filter when restoring data items (DHIS2-15816) [v38]

---

.github/workflows/dhis2-verify-app.yml
package.json
src/api/Dimension.js
src/api/Layout.js
yarn.lock

Implements [DHIS2-15691](https://jira.dhis2.org/browse/DHIS2-15691)
**Requires https://github.com/dhis2/d2-analysis/pull/153**
After:
[DHIS2-15691]: https://dhis2.atlassian.net/browse/DHIS2-15691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: enr agg endpoint + do not req stage for attr and pi (DHIS2-15691)

---

.github/workflows/dhis2-verify-app.yml
package.json
src/api/Dimension.js
src/api/Layout.js
yarn.lock

Backport of https://github.com/dhis2/event-reports-app/pull/1334

fix: enr agg endpoint + do not req stage for attr and pi [v40] (DHIS2-15691)

---

.github/workflows/dhis2-verify-app.yml
package.json
src/api/Dimension.js
src/api/Layout.js
yarn.lock

Backport of https://github.com/dhis2/event-reports-app/pull/1334

fix: enr agg endpoint + do not req stage for attr and pi [v39] (DHIS2-15691)

---

.github/workflows/dhis2-verify-app.yml

Install prerequisites for `pngquant`.

chore: install libpng-dev as prereq

---

.github/workflows/dhis2-verify-app.yml
package.json
yarn.lock

Adds d2-analysis@33.3.4 which passes withCredentials=true with ajax requests.

fix: pass withCredentials

---

index.html

Backports https://github.com/dhis2/event-reports-app/pull/1386

fix: add base target top (DHIS2-19274)
