- package.json
- yarn.lock
The latest d2-analysis package will limit the number of mentions to 5, in the interpretations
Fixes [DHIS2-5483]
> Upgrade d2-analysis to get latest interpretations mentions

- package.json
- yarn.lock
The latest d2-analysis package will limit the number of mentions to 5, in the interpretations
Fixes [DHIS2-5483]
> Upgrade d2-analysis to get latest interpretations mentions v31

- package.json
- yarn.lock
Reverts dhis2/event-reports-app#42
Correct version for master is `32.0.3`, not `31.0.8`
> Revert "patch: bump d2-analysis version with interpretation sort order fix [DHIS2-5472]"

- package.json
- yarn.lock
This PR includes latest version of d2-analysis with interpretation [sort order fix](https://jira.dhis2.org/browse/DHIS2-5472)
> patch-v31: bump d2-analysis version with interpretation sort order fix [DHIS2-5472] 

- package.json
- yarn.lock
This PR includes latest version of d2-analysis with interpretation [sort order fix](https://jira.dhis2.org/browse/DHIS2-5472)
> fix:  update d2-analysis with interpretations sort order fix [DHIS2-5472]

- src/api/Layout.js
Fixes [DHIS2-5582](https://jira.dhis2.org/browse/DHIS2-5582?filter=-1).
This PR enables default sorting (by `eventdate`)  settings for events.
> feat: sort by event date by default for events

- package.json
- yarn.lock
Relates to [DHIS2-2480](https://jira.dhis2.org/browse/DHIS2-2480).
- Upgrade `d2-analysis` dependency version to 33.0.1
> chore: Upgrade d2-analysis to enable incident/enrollment dates for events

- package.json
- yarn.lock
Relates to [DHIS2-2757](https://jira.dhis2.org/browse/DHIS2-2757).
- Updating `d2-analysis` version to 33.0.2 to enable event date labels.
> chore: Upgrade d2-analysis to enable event date label.

- package.json
- yarn.lock
Relates to [DHIS2-2757](https://jira.dhis2.org/browse/DHIS2-2757).
- Updating `d2-analysis` library version to 33.0.3 enabling labels for incident/enrollment dates.
> chore: Update d2-analysis

- index.html
- src/css/style.css
App styles (`body * { font-family: Helvetica Neue, sans-serif !important }`) cause font issues on plugin import in other apps (e.g. dashboards app).
Proposed changes make styles more specific to event reports app by using body class selector.
> fix: Make styles more specific to app/plugin

- CHANGELOG.md
- package.json
- src/actions/current.js
- src/actions/visualization.js
- src/components/App.js
- src/components/Toolbar/MenuBar.js
- src/components/Toolbar/Toolbar.js
- src/components/Toolbar/styles/MenuBar.module.css
- src/configureStore.js
- src/reducers/current.js
- src/reducers/index.js
- src/reducers/visualization.js
The PR has a bit more than that, since navigation had to be implemented too.
Now it's possible to load a ER (Line list only) visualization from the `FileMenu` or from the URL.
Both `visualization` and `current` are set when a visualization is loaded.
The actual fetch uses `useDataQuery` hook directly in the `App` component.
The New button in the FileMenu also works and cleans the Redux store.
* Some parts from DV have been omitted but we likely need them, for example the loading of the visualization from the user data store.
* I'm not sure about the interpretation part, since the component is going to be rewritten from scratch. In current DV the URL can contain the interpretation id and in that case the right panel opens showing the interpretation.
> feat: FileMenu in MenuBar and loading of visualization

- src/components/App.js
- src/components/Visualization/Visualization.js
* store metadata from the analytics response in the store
* use item names instead of ids in the `DataTable`
The `DataTable` looks much better now:
> feat: populate metadata in store and use it to display item names in DataTable

- .github/pull_request_template.md
The template is already in `develop`, but it needs to go on the `master` branch for GH to pick it up
Copied from https://github.com/dhis2/event-reports-app/blob/develop/.github/pull_request_template.md
> chore: add the pr template from DV

- src/components/App.module.css
- src/components/Visualization/Visualization.js
- src/components/Visualization/styles/Visualization.module.css
1. Makes the data-table have an automatic layout/width
2. Adds the relativePeriodDate prop
---
The datatable is now horizontally centered and has an automtic width. The auto-width feature is visible in the specs and I know from other apps I've recently worked on that this is a required functionality. However,if we want to keep showing the TitleBar before the datatable is ready, and the keep it seperate from the datatable, we can't left align the table and center-align the title above it. So in the end we need to decide between two options:
A. Put the title into the table, and accept this isn’t rendered when the table is loading. (we would have to find some way to not render the title when in a plugin)
B. Center the table and title as in the screenshot.
---
-   [ ] Check with Joe about the …
> fix(visualization): make table auto-width + add relativePeriodDate prop

- src/components/Toolbar/VisualizationTypeSelector/VisualizationTypeSelector.js
1. remove the onClick handler for the disabled types in the visualization type selector
---
Nothing should happen when a disabled item is clicked in the visualization type selector.
> fix: remove onClick handler for disabled types in vis type selector

- i18n/en.pot
- src/components/App.js
- src/components/DetailsPanel/DetailsPanel.js
- src/components/InterpretationModal/InterpretationModal.js
- src/components/InterpretationModal/interpretationIdQueryParam.js
- src/components/Interpretations/InterpretationModal/InterpretationModal.js
- src/components/Interpretations/common/Interpretation/Interpretation.js
- src/components/Visualization/Visualization.js
- src/components/Visualization/styles/Visualization.module.css
- src/components/Visualization/useAnalyticsData.js
Implements [TECH-825](https://jira.dhis2.org/browse/TECH-825)
---
1. Use SWR in the `Visualization` component to avoid content shifts when interacting with the visualisation in the modal
2. Extract the `Visualization` component's data fetching logic into a hook
3. Show loading errors in the `Visualisation` component
4. Fix content shift in the modal on first load
5. Switch the global `isVisualizationLoading` state to `false` when closing the modal
---
I've reworked the Visualization component a bit. The code has been refactored so that the data logic is extracted into a hook. Functionality-wise I've also added support for rendering errors, but the biggest change is that this component now uses the SWR model. **S**tale **W**hile **R**evalidate means that we keep the old data in place while …
> TECH-825-modal-open-content-shift

- src/modules/visualization.js
1. fix incorrect visualization `type`
---
Saving an ER AO was failing due to a non-recognised value for `type`.
The correct 2 types are `LINE_LIST` and `PIVOT_TABLE`.
> fix: fix visualization types passed to the AO

- src/components/App.js
- src/components/Dialogs/Conditions/BooleanCondition.js
- src/components/Dialogs/Conditions/ConditionsManager.js
- src/reducers/legendSets.js
Implements [TECH-815](https://jira.dhis2.org/browse/TECH-815)
Continues / extends https://github.com/dhis2/event-reports-app/pull/882
---
1. Hides `false` from the `BooleanCondition` to facilitate `TRUE_ONLY`
---
`TRUE_ONLY` is a boolean without a `false` option. Hence `BooleanCondition.js` was adapted to facilitate both the regular `BOOLEAN` and the new type.
---
> feat: TRUE_ONLY condition type (TECH-815)

- i18n/en.pot
- src/components/Dialogs/Conditions/AlphanumericCondition.js
- src/components/Dialogs/Conditions/BooleanCondition.js
- src/components/Dialogs/Conditions/ConditionsManager.js
- src/components/Dialogs/Conditions/DateCondition.js
- src/components/Dialogs/Conditions/NumericCondition.js
- src/modules/conditions.js
Implements [TECH-817](https://jira.dhis2.org/browse/TECH-817)
Spec: [ER:C6: Condition selector](https://docs.google.com/document/d/1qrcLpVymdBpgzJyJ3IPULtotCQdg2PWnQL-AlgntMz4/edit#)
---
1. Implement date, datetime, time conditions
2. Refactor all other condition types to follow the same prop signature
---
_feat_: Generally follows the pattern used for the numeric, alphanumeric and boolean conditions to implement date / datetime / time conditions. Main exception is that instead of having a single export with props to toggle various parts, separate exports for each sub-type are used.
_refactor_: All the previous condition types have all been refactored to use this new format with separately exported components rather than proprietary props unique to each condition type. This results in all …
> feat: date, datetime, time conditions (TECH-817)

- i18n/en.pot
- src/components/Dialogs/Conditions/ConditionsManager.js
Implements [TECH-884](https://jira.dhis2.org/browse/TECH-884)
---
1. Display a static text for non-filterable dimensions
---
Simply wraps all conditions output in a check to make sure `valueType` (called `dimensionType`) is available, if not its assumed to be a non-filterable type.
---
> feat: show static text for non-filterable dims (TECH-884)

- src/components/DownloadMenu/ToolbarDownloadDropdown.js
1. Fix bug in DownloadMenu
---
The DownloadMenu opened from the Toolbar couldn't be closed by clicking outside of it.
> fix: close the DownloadMenu when clicking outside of it

- src/api/options.js
- src/components/App.js
- src/components/Dialogs/Conditions/OptionSetCondition.js
Implements [TECH-816](https://jira.dhis2.org/browse/TECH-816)
---
1. Saves and fetches metadata for options that previously only had `code`
---
Options use `code` as their identifier instead of `id`. This led to some issue with metadata (`name`) being missing from options that weren't "in scope" in the `Transfer` component (e.g. select an option and then applying a filter which would exclude said option would lead to the name being missing. As seen in the screenshot here: https://github.com/dhis2/event-reports-app/pull/887).
The solution was to make sure that the metadata is added to the store when options were selected plus fetching that metadata for the list of `selected` options.
---
-   [ ] As the `onChange` callback is fired _every_ time a change is made (even if things were only …
> fix: save and fetch options to/from metadata with code (TECH-816)

- src/api/legendSets.js
- src/components/Dialogs/Conditions/ConditionsManager.js
Implements [TECH-788](https://jira.dhis2.org/browse/TECH-788)
---
1. Display program indicators as numeric condition
2. Refactor names (`DIMENSION_TYPE` -> `VALUE_TYPE`)
---
Displays program indicators as a numeric condition by consolidating the numeric condition code into a function that's used by `valueType` numeric + `dimensionType` program indicator, both of which can also have legend sets. Also refactors the names of the consts, to differentiate between `valueType` and `dimensionType`, which were mixed up before.
> fix: program indicators as numeric condition (TECH-788)

- src/components/Visualization/useAnalyticsData.js
This avoids undefined or nothing to be displayed in the data table.
---
1. avoid undefined to be shown in the data table for BOOLEAN value types
2. avoid empty cell to be shown in the data table for TRUE_ONLY value types
---
Values for both BOOLEAN and TRUE_ONLY value types can be empty.
Before `undefined` or nothing were shown as value in the data table.
`Not answered` should be shown instead to match the same text used in the condition dialog.
---
Before:
After:
> fix: format empty value for BOOLEAN and TRUE_ONLY

- src/components/Dialogs/Conditions/AlphanumericCondition.js
- src/modules/conditions.js
Implements [TECH-812](https://jira.dhis2.org/browse/TECH-812)
---
1. Case sensitive checkbox default state is unchecked
2. Case sensitive checkbox now properly reflects the backend operator (unchecked -> `ILIKE`, checked -> `LIKE`)
> fix: alphanumeric case sensitive state (TECH-812)

- src/components/Visualization/Visualization.js
- src/components/Visualization/styles/Visualization.module.css
No issue number available
---
1. Shows an overlay over the table-body only, as before, so users could theoretically interact with the column headers while the table data is being refreshed.
2. Shows the spinner from a wrapper element which has the same height as the table scollbox, so this will always remain in view
---
> fix: keep spinner in view when scrolling data-table

- src/components/Visualization/useAnalyticsData.js
Relates to [DHIS2-12314](https://jira.dhis2.org/browse/DHIS2-12314)
---
1. pass the new `headers` query parameter to analytics request
2. refactor the code for generating the table content
---
The list of headers to request is directly mapped from the `visualization.columns` and in the same order, so reordering the chips in the layout allows to reorder the data in the rows.
Some columns need special handling during the mapping:
* `ou` is replaced with `ouname`
* `pe` is removed
* all date dimensions selected in the left sidebar should be added
This also simplifies populating the data table and reduces the payload in the analytics response by removing unused headers that otherwise are returned by default.
---
-   [ ] once the date selector on the left sidebar is in place, those date fields …
> fix: pass headers in the analytics request DHIS2-12314

- src/components/App.module.css
- src/components/Visualization/Visualization.js
- src/components/Visualization/styles/Visualization.module.css
- src/components/Visualization/useAvailableWidth.js
No issue number available
---
1. Limit table scrollbox width to available width
2. Animate scrollbox width with the same animation as the panels so everything looks smooth
---
> feat: visualization scrollbox auto-width

- src/components/Visualization/useAnalyticsData.js
- src/modules/current.js
**Requires https://github.com/dhis2/analytics/pull/1134**
---
1. set `outputType` in current based on the Input selector
2. use the correct analytics endpoint based on `outputType`
---
Note: in 2.38 only Line List is supported
Line List:
Input: Event -> `/analytics/events/query/...`
Input: Enrollment -> `/analytics/enrollments/query/...`
Pivot Table:
Input: Event -> `/analytics/events/aggregate/...`
Input: Enrollment -> `/analytics/enrollments/aggregate/...`
---
-   [x] update analytics dep once https://github.com/dhis2/analytics/pull/1134 is merged
Example of 2 requests when toggling Input from Event to Enrollment:
> fix: use the correct analytics endpoint based on outputType

- i18n/en.pot
- src/middleware/metadata.js
When an array is picked up by the metadata middleware it no longer dispatches every item, but creates a single object with all the keys and dispatches once.
This PR also removes the doubled up `typeof` check.
Before (this example is from loading a saved visualization):
After:
> fix: only dispatch once in metadata middleware

- src/api/legendSets.js
- src/components/App.js
- src/components/Dialogs/Conditions/ConditionsManager.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsFilter.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/useProgramDimensions.js
- src/modules/visualization.js
Implements [TECH-964](https://jira.dhis2.org/browse/TECH-964)
---
1. convert PROGRAM_DATA_ELEMENT to DATA_ELEMENT dimensions
---
When opening an AO, some dimensions have `PROGRAM_DATA_ELEMENT` `dimensionType` which causes conflicts in the new ER app.
This PR converts all such dimensions in `columns` and `filters` before storing `current` in the Redux store.
Before:
After:
> fix: convert PROGRAM_DATA_ELEMENT to DATA_ELEMENT dimensions (TECH-964)

- src/AppWrapper.js
Buggy behaviour when loading an ER. Sometimes layout would be populated, and sometimes not. The issue was that there are two separate redux stores being read/written.
---
Fix was to remove state (ouLevels). ouLevels is not currently in use anyway, but a comment was also added to remind us to not add state to this component in the future.
> fix: remove state in AppWrapper that was causing multiple instances of redux store

- src/actions/ui.js
- src/components/MainSidebar/InputPanel/InputPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/reducers/__tests__/ui.spec.js
- src/reducers/ui.js
Additional fix to [DHIS2-874](https://jira.dhis2.org/browse/DHIS2-DHIS2-874)
---
1. Program and stage are not longer cleared after loading a saved visualisation
2. `CLEAR_UI_PROGRAM_ID` was renamed to `CLEAR_UI_PROGRAM`, because it doesn't just clear the program's `id` field, but also the `stageId`.
---
Action sequence after the fix: no more `CLEAR_UI_PROGRAM` and `CLEAR_UI_STAGE` after `SET_UI_FROM_VISUALIZATION`
> fix: prevent clearing program and stage after loading saved visualization

- src/components/Visualization/Visualization.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/visualization.js
Implements [TECH-869](https://jira.dhis2.org/browse/TECH-869) and [TECH-960](https://jira.dhis2.org/browse/TECH-960)
---
1. convert `pe` dimension to a time dimension when opening a "old format" AO [(TECH-869)](https://jira.dhis2.org/browse/TECH-869)
2. format column values to pass to `headers` in the analytics request ([TECH-960](https://jira.dhis2.org/browse/TECH-960))
3. pass the time dimensions as arguments in the analytics request
4. set default sorting to first column ascending
---
The new time dimensions that can be added to Columns/Filters require special handling in the analytics request.
1. they need to be passed in `headers` like the other dimensions but lowercased
2. they need to be passed as query arguments in the analytics request instead of as `dimension` argument
---
- …
> feat: forward compatibility: pe - time dimension conversion TECH-796

- src/components/MainSidebar/MainDimensions.js
Implements KFMT point
See[ this Slack thread](https://dhis2.slack.com/archives/G01PW9YGZD2/p1644251159031399)
---
1. Stop disabling all main dimensions while the program is unknown
2. Keep disabling the program and event status dimension, because they depend on program type, so shouldn't be available when the program is not known.
---
> fix(main-dimensions): only disable event and program status

- src/components/MainSidebar/ProgramDimensionsPanel/StageSelect.js
- src/components/MainSidebar/ProgramDimensionsPanel/__tests__/useProgramDimensions.spec.js
- src/components/MainSidebar/ProgramDimensionsPanel/useProgramDimensions.js
Implements issue nr not available
---
1. Use `id:startsWith:<ID>` instead of `id:like:<ID>` to filter data element dimensions
2. Ensure the stage ID is not added to the global store when `STAGE_ALL` is selected
---
-   [ ] We are sending the correct query params to the server but the filter still doesn't seem to be working.
---
> chore: fix prgram stage filter

- package.json
- src/components/Visualization/useAnalyticsData.js
- yarn.lock
**Requires https://github.com/dhis2/analytics/pull/1150**
---
1. remove `stage` from analytics request
2. use latest analytics with program stage prefix handling for dimensions
---
In ER the program stage id is required to be prefixed to the dimension id when assembling the analytics request.
The specific `stage` query parameter is not required.
> fix: program stage analytics handling

- package.json
- src/modules/current.js
- yarn.lock
**Requires https://github.com/dhis2/analytics/pull/1158**
---
1. nest `programStage` object within the dimension object
---
In `ui` we store the `programStage` id prefixed to the `dimension` id.
This format is not working for the AO, so we need to convert to the
expected format when generating `current`.
---
Before:
After:
> fix: format dimension object with programStage

- src/components/Visualization/useAnalyticsData.js
1. add programStageId to dimensionId passed in analytics headers
---
This is required for the analytics request to work.
The format is the same as what is used for passing `dimensions`: `<programStageId>.<dimensionId>`
---
Before:
which causes this error:
After:
> fix: prefix programStageId to dimensionId in analytics headers

- src/components/Dialogs/DialogManager.js
- src/components/Toolbar/VisualizationTypeSelector/VisualizationTypeListItem.js
- src/components/Toolbar/VisualizationTypeSelector/VisualizationTypeSelector.js
I also took the opportunity to switch DialogManager from `connect` to `useDispatch` and `useSelector`.
And `rootOrgUnits` was not in use
> fix: remove console warnings due to component props

- i18n/en.pot
- src/actions/ui.js
- src/components/Dialogs/DialogManager.js
- src/components/Dialogs/PeriodDimension/PeriodDimension.js
- src/components/Dialogs/PeriodDimension/PeriodDimension.module.css
- src/components/Dialogs/PeriodDimension/StartEndDate.js
- src/components/Dialogs/PeriodDimension/StartEndDate.module.css
- src/components/Dialogs/PeriodDimension/index.js
- src/components/Visualization/useAnalyticsData.js
Implements [DHIS2-TECH-963](https://jira.dhis2.org/browse/DHIS2-TECH-963)
---
1. Opens period dimension modal when clicking on time dimension items
2. Updates `metadata`, `ui` and `current` store with selected items
---
-   [ ] Implement proper display names for items that are preselected when a saved visualization is loaded
---
-   [ ] Preselected items show their ID as name because the backend currently doesn't return metadata for selected period dimensions (see [this Slack thread](https://dhis2.slack.com/archives/G3TL0J145/p1645099048878379?thread_ts=1645093552.964819&cid=G3TL0J145))
---
> feat: time dimensions dialog

- src/components/Visualization/useAnalyticsData.js
- src/modules/visualization.js
Related to [DHIS2-12482](https://jira.dhis2.org/browse/DHIS2-12482) and [TECH-960](https://jira.dhis2.org/browse/TECH-960)
---
1. do not pass `createdBy` and `lastUpdatedBy` as dimensions in the analytics request
2. pass `createbydisplayname` and `lastupdatebydisplayname` when `createBy` and `lastUpdatedBy` dimensions are dragged into Columns
---
`createdBy` and `lastUpdatedBy` don't have a value selection, so they cannot be passed as dimensions, doing so results in an error (see Before screenshot).
However, they can be passed in `headers` so that analytics can return the data to display and they can be used for sorting the table.
(The error in the After screenshot is unrelated to this)
---
Before:
After:
> fix: createdB lastUpdatedBy dimension handling for analytics

- src/components/Visualization/useAnalyticsData.js
1. pass ids with repetition indexes to analytics `headers`
---
When repeatable events are used, the dimension ids passed to analytics `headers` should match the ones passed in `dimension`, they should contain the repetition index.
Before:
After:
> fix: format analytics header with repetitions

- i18n/en.pot
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/StageSelect.js
Implements KFMT issue, see thread (I meant to make this into a link, but Slack is down for me)
---
1. Previously, we would only auto-select a program-stage in specific situaltions which only had a single artificial stage. Now we have generalised that a bit mnore, we will simply auto-select a stage if there is only 1 available.
2. Hide optional stage-select (below the type-select) in program-dimensions-filter component if only a single stage is found
3. Hide required stage-select (below the program select) in program-select component if only a single stage is found
---
|  Input type | With single stage | With multiple stages |
| ------------- | ------------- |------------- |
| Event  | <img width="530" alt="Screenshot 2022-02-23 at 12 41 12" …
> feat: auto-select program stage and hide select if only one is present

- src/modules/__tests__/timeDimensions.spec.js
- src/modules/timeDimensions.js
I restored the tests that broke yesterday when I removed the `scheduledDate` dimension. Since this dimsnion is going to be added in the future, I decided to just comment everything out relating to that dimension, instead of deleting the code. So this PR doesn't contain any real changes, it's just a restoration of what we had in place already.
> fix: restore-time-dimension-tests

- src/components/Toolbar/VisualizationTypeSelector/styles/VisualizationTypeSelector.module.css
1. fix vis type selector styles
---
Before:
After:
> fix: remove grey area below the vis type selector

- src/components/App.js
When loading a saved eventVisualization we need to ask for the `repetition` field.
> fix: adds repetition to fields

- src/components/DndContext.js
- src/components/MainSidebar/DimensionItem/DimensionItem.js
1. include valueType when setting metadata while dragging dimension items
---
https://user-images.githubusercontent.com/6113918/155508846-43e0368d-d25a-44f2-9594-366b51a7821f.mov
> fix: include valueType when setting metadata while dragging dimension items

- i18n/en.pot
- src/components/MainSidebar/MainSidebar.js
- src/components/MainSidebar/YourDimensions.js
- src/components/MainSidebar/YourDimensionsMenuItem.js
- src/components/MainSidebar/YourDimensionsPanel/useYourDimensions.js
1. hide your dimensions button if no your dimensions are available
---
Moved the menu item for Your dimensions into a separate component which queries the `dimensions` endpoint to check if any dimension is available.
If not, hide the button as clicking it would result in an empty list in the panel.
> fix: hide your dimensions button when no dimensions are available

- src/components/App.module.css
1. show a border on the left of the right sidebar when open
---
The border between the right sidebar and the main content was missing when the sidebar is open.
---
Before:
After:
> fix: use a left border on right sidebar when open

- src/components/MainSidebar/MainSidebar.js
- src/components/MainSidebar/MenuItem/MenuItem.js
- src/components/MainSidebar/MenuItem/MenuItem.module.css
Implements KMFT point from [this Slack thread](https://dhis2.slack.com/archives/G3TL0J145/p1645628699820989)
---
1. If no program is selected the program dimension menu item count badge now gets a custom dashed style
2. The badge will still display if count equals `0` (before it would not render)
3. I noticed that when a menu item is selected and being hovered, the color of it is very close to the color of the badge, so I added an additional style to remedy this.
---
Reg point 3 above, I guess mainly for @cooper-joe:  I think it'd make more sense to go with teal for these badges instead of grey. Firstly because teal is the color we have associated with "selection" in our design system. Secondly because that would fix the issue with the hover-styles and badge styles colliding in a more …
> feat: show dashed style on program dimension badge if no program is selected

- src/modules/metadata.js
Implements [TECH-989](https://jira.dhis2.org/browse/TECH-989)
---
1. add missing metadata for THIS_MONTH
---
THIS_MONTH is the default item selected for the period dimension. ie. when you click New or start the app without a id in the URL.
Before:
After:
> fix: add metadata for default period TECH-989

- src/AppWrapper.js
- src/components/App.js
Implements [TECH-998](https://jira.dhis2.org/browse/TECH-998)
---
1. click on New should reset the app
---
Before it only happened on the 2nd click on New.
I'm not sure about the logic of the navigation, while debugging I
noticed that `previousLocation` is always `undefined` on the next
navigation, so the whole thing seems to work only because we use
location state which covers the cases where the URL remains the same (ie. open the same AO from the FileMenu, click on New multiple times...) but we still want to refresh the page.
The other case is to load the visualization when the location changes,
and that check is always true due to `previousLocation` being `undefined` and compared to `/` or `/[id]`.
This fixes the issue, and everything seems to work, but the logic needs to be reviewed. …
> fix: reset app when New is clicked

- src/components/Visualization/Visualization.js
- src/components/Visualization/styles/Visualization.module.css
Implements Visualization sizes from options 
---
1. Data table cells are padded according to the "Display density" option
2. Data table cells get a font size from the "Font size" option 
---
This PR comes with some notes:
- The data-table component from @dhis2/ui did already come with a `large` prop, but no `small` prop was available yet, and this is not planned either. Joe advised to apply custom styling in the app, which I did.
- Changing the content of the pagination is a bit tricky. So it was discussed that for the MVP we just decrease the padding a bit when the dispaly density changes. 
---
-   [ ] The data table in `@dhis2/ui` uses a slightly different padding and font-size for the header cells than for the body cells. We probably need to do the same for this custom data-table. I've …
> feat: apply font size and padding based on settings

- src/components/MainSidebar/YourDimensionsMenuItem.js
1. `selected` prop was required but its value can be `undefined`
---
The `selected` prop was throwing a warning about being required but its
value being undefined.
Use the same prop types definitions as in `MenuItem`.
> fix: avoid warning about failed prop type

- i18n/en.pot
- src/modules/repetition.js
- src/modules/ui.js
Parses the `repetition` field for each dimension to `repetitionByDimension` when loading a visualiation.
---
> fix: parse repetition when loading a visualization

- src/actions/ui.js
- src/components/Dialogs/PeriodDimension/PeriodDimension.js
- src/modules/__tests__/timeDimensions.spec.js
- src/modules/metadata.js
- src/modules/timeDimensions.js
- src/reducers/ui.js
Implements:
- [TECH-979](https://jira.dhis2.org/browse/TECH-979)
- A number of KFMT issues related to period/time dimensions
---
1. Use names from metadata to set initially selected period items ([TECH-979](https://jira.dhis2.org/browse/TECH-979))
2. Tweak default time dimension selection, see [Slack thread](https://dhis2.slack.com/archives/G3TL0J145/p1645628057636699)
3. Clear time dimensions from layout when switching Input / program, see [Slack thread](https://dhis2.slack.com/archives/D9N90FGCQ/p1645613457823179)
---
Below some details about the key features:
1. Since the backend is now including the names of the period dimension items in the `metadata.items` in the analytics response, it is now possible to start using these names for the intitially selected period dimensions.
2. The …
> fix: time dimension improvements

- i18n/en.pot
- src/components/Interpretations/common/Interpretation/InterpretationSharingLink.js
- src/components/Interpretations/common/Interpretation/InterpretationUpdateForm.js
- src/components/Interpretations/common/Interpretation/index.js
Implements [TECH-1001](https://jira.dhis2.org/browse/TECH-1001)
---
1. allow to edit interpretations' sharing settings
---
This feature is present in the old `d2-ui` implementation.
Together with @janhenrikoverland we decided to remove the sharing access summary for now, the string can easily become too long if we should use the same format used in the About visualization panel.
Only the `Manage sharing` button is shown.
---
> fix: add button for opening Sharing dialog for interpretation

- src/actions/ui.js
- src/actions/visualization.js
- src/api/legendSets.js
- src/components/App.js
- src/components/Dialogs/Conditions/ConditionsManager.js
- src/components/Dialogs/DialogManager.js
- src/components/Dialogs/FixedDimension.js
- src/components/Layout/ChipBase.js
- src/components/MainSidebar/DimensionItem/DimensionIcon.js
- src/components/MainSidebar/DimensionItem/DimensionItemBase.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsFilter.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/useProgramDimensions.js
- src/components/MainSidebar/SelectedDimensionsContext.js
- src/components/Visualization/Visualization.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/__tests__/timeDimensions.spec.js
- src/modules/dimensionConstants.js
- src/modules/dimensionTypes.js
- src/modules/layoutValidation.js
- src/modules/mainDimensions.js
- src/modules/metadata.js
- src/modules/timeDimensions.js
- src/modules/visualization.js
- src/reducers/ui.js
1. Rename constants from "_TYPE_" to "_ID_" to clearly differentiate between them (and rename file dimensionTypes.js to dimensionConstants.js)
2. create 2 dimension Types for determining dimension icon and which modal to open: DIMENSION_TYPE_STATUS and DIMENSION_TYPE_USER 
3. DialogManager now only considers dimensionType when deciding which modal to open
4. Set correct dimension icon on chips
> fix: time and main dimension constants should use _ID_ rather than _TYPE_

- src/components/Layout/Chip.js
Implements KFMT issue, see [Slack thread](https://dhis2.slack.com/archives/G01PW9YGZD2/p1646044031725009)
---
1. Hides the skeleton chips when there visualization has a load error
---
> fix: do not show blank chips after visualization load error

- src/actions/ui.js
Implements KFMT issue, see [Slack thread](https://dhis2.slack.com/archives/G01PW9YGZD2/p1646055456402139?thread_ts=1646055281.685329&cid=G01PW9YGZD2) and [TECH-1006](https://jira.dhis2.org/browse/TECH-1006)
---
The problem was more widespread than just the OU dimension being cleared. There was a flaw in my logic, because I was previously adding all the dimension which were a program dimension, or not in the list of enabled time dimensions to `idsToRemove`. But when doing so, I obviously forgot to check if that ID I was about to add to `idsToRemove` was indeed a period dimension 🤦 .
---
> fix: prevent clearing org unit dimension

- i18n/en.pot
- src/actions/ui.js
- src/components/DimensionMenu/DimensionMenu.js
- src/components/MainSidebar/DimensionItem/DimensionItem.js
Implements KMFT issue, see [Slack thread](https://dhis2.slack.com/archives/G01PW9YGZD2/p1646042397493249)
---
1. Prevents app crashing when adding a dimension to filter/column via the chip menu
---
This issue was only relevant to dimensions originating from the DB, so only "program" and "your" dimensions. 
---
> fix: add dimension to metadata when adding from chip menu

- src/components/DownloadMenu/useDownloadMenu.js
- src/components/Visualization/useAnalyticsData.js
Implements [TECH-1000](https://jira.dhis2.org/browse/TECH-1000)
---
1. fix URLs used for download
2. don't pass query parameter with `undefined` value
---
URLs used for download also use the analytics endpoint and need to pass the dimensions and time dimensions in the same fashion as the main analytics request for data.
For some parameter like `eventStatus` and `programStatus` there could be an empty item selection.
In that case, the parameter should not be added to the query string, otherwise it causes errors due to their value being `undefined`.
Example:
> fix: URLs used for download

- src/actions/visualization.js
- src/modules/dimensionConstants.js
Fixes an unreported bug where saving an AO with eventStatus then reopening, the wrong dialog is opened when clicking to edit the dimension.
eventStatus, programStatus, createdBy and lastUpdatedBy all have dimensionType 'DATA_X' from the backend. But the frontend needs to differentiate between "status" types and "user" types for opening the correct dialog, and showing the correct icon.
This PR sets the dimensionType relevant for ui. This does not affect saving the AO, as the dimensionTypes are not copied into current when updating. (setCurrentFromUi)
https://user-images.githubusercontent.com/6113918/156143971-ba13c4de-86a6-487b-abfb-bba7ede6ab7f.mov
)
> fix: set customized ui-only dimensionType for eventStatus, programStatus, createdBy, lastUpdatedBy

- src/components/Dialogs/Conditions/ConditionsManager.js
1. remove debug text in conditions dialog
---
Before:
After:
> fix: remove debug text from conditions dialog

- src/components/Visualization/Visualization.js
Implements [TECH-1008](https://jira.dhis2.org/browse/TECH-1008)
---
1. format event/enrollment/incident dates
---
Remove the timestamp and format according to the instance locale and
date format preferences.
---
Before:
After:
> fix: format event/enrollment/incident dates (TECH-1008)

- src/modules/ui.js
1. fix chip dialog to correctly show the condition
---
The unprefixed ids caused the chip to not show the selected condition correctly.
This only happened if the dimension has a program stage set.
Before the id used as key in `conditions` was not prefixed with the program stage id, causing the lookup from the chip to fail.
---
Before:
After:
> fix: chip not showing the selected condition

- src/components/DetailsPanel/DetailsPanel.js
- src/components/Interpretations/InterpretationModal/InterpretationModal.js
- src/components/Interpretations/InterpretationModal/useModalContentWidth.js
- src/components/Interpretations/InterpretationsUnit/InterpretationForm.js
- src/components/Interpretations/InterpretationsUnit/InterpretationList.js
- src/components/Interpretations/InterpretationsUnit/InterpretationsUnit.js
- src/components/Interpretations/common/Interpretation/Interpretation.js
- src/components/Visualization/Visualization.js
- src/components/Visualization/useAvailableWidth.js
Implements [TECH-1005](https://jira.dhis2.org/browse/TECH-1005)
_And some other issues with the interpretations modal_
---
1. Adds whitespace below the title and prevent the characters from being clipped
2. Implement calculated widths for both the modal content and the visualization, to prevent a horizontal scrollbar from appearing
3. Disable interpretation thread when there is a visualization load error
---
-  Both the modal content and the visulaization are using a computed width based on the window width. The `InterpretationsModal` component is going to go into analytics, and the `Visualization` component is staying in the app, or will be a separate analytics component. As such, I didn't see much opportunity for code-sharing right now, so I have a bit of duplicated logic.
---
*Disabled …
> fix: address interpretation modal regressions

- i18n/en.pot
- package.json
- src/components/Visualization/Visualization.js
- src/components/Visualization/useAnalyticsData.js
- yarn.lock
Implements client side work of [DHIS2-12529](https://jira.dhis2.org/browse/DHIS2-12529)
---
1. Upgrades `@dhis2/ui` to `8.1.0` which includes support for pagers without a total in the `Pagination` component
2. Adds `totalPages=false` query param to the analytics request (not working yet)
3. Updates the props passed to`Pagination` to align with the new pager object shape
-   [ ] This isn't working yet because the backend is still returning a full pager object (with totals) after adding the query params.
---
_Can be added once the backend issue is fixed_
> fix: use visualization without total in pager

- package.json
- src/ui/DownloadButtonItems.js
- yarn.lock
_No issue number available_
**Requires https://github.com/dhis2/d2-analysis/pull/148*
---
1. This PR adds a classname to an element which can be used by push analytics to convert a visualization to HTML.
> feat: add class-name for push-analytics

- package.json
- src/ui/DownloadButtonItems.js
- yarn.lock
Upgrade d2-analysis and add a class-name directly in the app to allow push-analytics to find the right elements with use text selectors
> fix: add class-name for push-analytics

- package.json
- push-analytics.json
Related to [DHIS2-15367](https://dhis2.atlassian.net/browse/DHIS2-15367) in JIRA and push-analytics [PR#10](https://github.com/dhis2/push-analytics/pull/10)
---
1. Adds a JSON file with scrape instructions which push-analytics can use to convert a dashboard item for this app.
2. During the build process this file is copied to root directory of the app
---
[DHIS2-15367]: https://dhis2.atlassian.net/browse/DHIS2-15367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(push-analytics): add push analytics instructions

- package.json
- yarn.lock
Fixes [DHIS2-17631](https://jira.dhis2.org/browse/DHIS2-17631)
[DHIS2-17631]: https://dhis2.atlassian.net/browse/DHIS2-17631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: migrate away from deprecated userCredentials object (DHIS2-17631)

- index.html
Implements [DHIS2-19274](https://jira.dhis2.org/browse/DHIS2-19274)
Sets base target to `_top` to make links work in the dhis2 global shell.
[DHIS2-19274]: https://dhis2.atlassian.net/browse/DHIS2-19274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add base target top (DHIS2-19274)
